-- MySQL Script generated by MySQL Workbench
-- Wed Dec  1 23:16:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetobd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetobd` ;

-- -----------------------------------------------------
-- Schema projetobd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetobd` DEFAULT CHARACTER SET utf8 ;
USE `projetobd` ;

-- -----------------------------------------------------
-- Table `projetobd`.`Jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetobd`.`Jogador` (
  `idJogador` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `idade` INT NULL,
  `lucro` INT NOT NULL,
  PRIMARY KEY (`idJogador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetobd`.`Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetobd`.`Conta` (
  `idConta` INT NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Jogador_idJogador` INT NOT NULL,
  PRIMARY KEY (`idConta`, `Jogador_idJogador`),
  INDEX `fk_Conta_Jogador1_idx` (`Jogador_idJogador` ASC) VISIBLE,
  CONSTRAINT `fk_Conta_Jogador1`
    FOREIGN KEY (`Jogador_idJogador`)
    REFERENCES `projetobd`.`Jogador` (`idJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetobd`.`Axie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetobd`.`Axie` (
  `idAxie` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `poder` VARCHAR(45) NOT NULL,
  `Conta_idConta` INT NOT NULL,
  PRIMARY KEY (`idAxie`, `Conta_idConta`),
  INDEX `fk_Axie_Conta_idx` (`Conta_idConta` ASC) VISIBLE,
  CONSTRAINT `fk_Axie_Conta`
    FOREIGN KEY (`Conta_idConta`)
    REFERENCES `projetobd`.`Conta` (`idConta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetobd`.`Supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetobd`.`Supervisor` (
  `idSupervisor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `idade` INT NULL,
  `horas` INT NOT NULL,
  `salario` DECIMAL NOT NULL,
  PRIMARY KEY (`idSupervisor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetobd`.`Supervisor_has_Jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetobd`.`Supervisor_has_Jogador` (
  `Supervisor_idSupervisor` INT NOT NULL,
  `Jogador_idJogador` INT NOT NULL,
  PRIMARY KEY (`Supervisor_idSupervisor`, `Jogador_idJogador`),
  INDEX `fk_Supervisor_has_Jogador_Jogador1_idx` (`Jogador_idJogador` ASC) VISIBLE,
  INDEX `fk_Supervisor_has_Jogador_Supervisor1_idx` (`Supervisor_idSupervisor` ASC) VISIBLE,
  CONSTRAINT `fk_Supervisor_has_Jogador_Supervisor1`
    FOREIGN KEY (`Supervisor_idSupervisor`)
    REFERENCES `projetobd`.`Supervisor` (`idSupervisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supervisor_has_Jogador_Jogador1`
    FOREIGN KEY (`Jogador_idJogador`)
    REFERENCES `projetobd`.`Jogador` (`idJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
